Repository vivek9828/NewsLoose, pull requests merged in 2020-10, with the labels that each got.

#17 Splash Screen close #4
  lib/main.dart
  lib/screens/splash_screen.dart
Labels: UI

#18 home.dart page UI and Functionality Update
  lib/helper/article.dart
  lib/helper/news.dart
  lib/screens/main screens/home.dart
Labels: UI, functionality

#22 Network Connectivity Check close #5
  lib/screens/splash_screen.dart
Labels: functionality
